# Generated by Django 5.1 on 2025-03-11 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danisman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uygunluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='danisman.danisman')),
            ],
            options={
                'unique_together': {('psychologist', 'day_of_week', 'start_time')},
            },
        ),
    ]
